name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.18.0-beta1'

    - name: Test
      run: go test -v ./... -coverprofile=coverage.out
    - name: Collect code coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.out
